Updated to build with GCC 4.7 via codeworkx <daniel.hillenbrand@codeworkx.de> [PATCH] fix build errors using gcc-4.7
Error: selected processor does not support ARM mode `smc #0`
error: DIV usage mismatch between arch/arm/boot/compressed/head.o and output
error: DIV usage mismatch between arch/arm/boot/compressed/misc.o and output
error: DIV usage mismatch between arch/arm/boot/compressed/decompress.o and output
error: DIV usage mismatch between arch/arm/boot/compressed/lib1funcs.o and output
error: DIV usage mismatch between arch/arm/boot/compressed/ashldi3.o and output"
Signed-off-by: Bryan Smith <zarboz@gmail.com>